name: Rails Continuous Integration # ワークフローの名前

on:
  push: # GitHubにpushされた時にワークフローを起動する

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run rubocop # Rubocopを実行する
        env:
          ROOT_PASS: root
          DB_NAME: db
          DB_USER: user
          DB_PASS: password
          DB_PORT: 3306
          TZ: Asia/Tokyo
        run: docker compose run app rubocop
