name: Rails Continuous Integration # ワークフローの名前

on:
  push:
    branches:
      - main # mainブランチにpushするときワークフローを実行する
  pull_request: # pull request作成時にワークフローを実行する

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: copy
        run: cp .env.template .env

      - name: build docker image # 環境変数を読み込んだdocker imageを構築する。
        run: docker compose build app

      - name: Run rubocop # Rubocopを実行する
        run: docker compose run app rubocop

  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy
        run: cp .env.template .env

      - name: Build docker image # 環境変数を読み込んだdocker imageを構築する。
        run: docker compose build app

      - name: Create DB
        run: |
        docker compose run app rails db:create
        docker compose run app rake db:schema:load


      - name: Run rspec
        run: docker compose run app rspec spec
